FROM python:3.11-slim

# Cegah Python tulis file .pyc & pastikan log muncul real-time
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Instal LibreOffice untuk konversi DOCX ke PDF
RUN apt-get update && apt-get install -y libreoffice-writer --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN alembic init alembic

# Install dos2unix
RUN apt-get update && apt-get install -y dos2unix --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .
COPY entrypoint.sh /entrypoint.sh

# Konversi CRLF ke LF, lalu berikan izin eksekusi
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]