"""inisialisasi_database

Revision ID: ed69ca73a74d
Revises: 
Create Date: 2026-04-13 01:56:51.470633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed69ca73a74d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('doc_type', sa.Enum('submission', 'reference', name='doctype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'failed', name='docstatus'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('check_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus'), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_jobs_id'), 'check_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_check_jobs_source_doc_id'), 'check_jobs', ['source_doc_id'], unique=False)
    op.create_index(op.f('ix_check_jobs_status'), 'check_jobs', ['status'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sentence_index', sa.SmallInteger(), nullable=False),
    sa.Column('page_number', sa.SmallInteger(), nullable=True),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('token_count', sa.SmallInteger(), nullable=True),
    sa.Column('char_count', sa.SmallInteger(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_document_id'), 'sentences', ['document_id'], unique=False)
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_is_valid'), 'sentences', ['is_valid'], unique=False)
    op.create_table('plagiarism_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_similarity_pct', sa.Float(), nullable=False),
    sa.Column('flagged_sentence_count', sa.Integer(), nullable=True),
    sa.Column('total_sentence_count', sa.Integer(), nullable=True),
    sa.Column('unique_source_count', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('clean', 'low', 'medium', 'high', name='verdict'), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['check_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_plagiarism_reports_id'), 'plagiarism_reports', ['id'], unique=False)
    op.create_table('sentence_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_sentence_id', sa.Integer(), nullable=False),
    sa.Column('target_sentence_id', sa.Integer(), nullable=False),
    sa.Column('cosine_similarity', sa.Float(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['check_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['target_sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_comparisons_id'), 'sentence_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_sentence_comparisons_is_flagged'), 'sentence_comparisons', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_sentence_comparisons_job_id'), 'sentence_comparisons', ['job_id'], unique=False)
    op.create_index(op.f('ix_sentence_comparisons_source_sentence_id'), 'sentence_comparisons', ['source_sentence_id'], unique=False)
    op.create_table('report_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('target_doc_id', sa.Integer(), nullable=False),
    sa.Column('matched_sentences', sa.Integer(), nullable=True),
    sa.Column('similarity_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['plagiarism_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_details_id'), 'report_details', ['id'], unique=False)
    op.create_index(op.f('ix_report_details_report_id'), 'report_details', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_details_report_id'), table_name='report_details')
    op.drop_index(op.f('ix_report_details_id'), table_name='report_details')
    op.drop_table('report_details')
    op.drop_index(op.f('ix_sentence_comparisons_source_sentence_id'), table_name='sentence_comparisons')
    op.drop_index(op.f('ix_sentence_comparisons_job_id'), table_name='sentence_comparisons')
    op.drop_index(op.f('ix_sentence_comparisons_is_flagged'), table_name='sentence_comparisons')
    op.drop_index(op.f('ix_sentence_comparisons_id'), table_name='sentence_comparisons')
    op.drop_table('sentence_comparisons')
    op.drop_index(op.f('ix_plagiarism_reports_id'), table_name='plagiarism_reports')
    op.drop_table('plagiarism_reports')
    op.drop_index(op.f('ix_sentences_is_valid'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_document_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_check_jobs_status'), table_name='check_jobs')
    op.drop_index(op.f('ix_check_jobs_source_doc_id'), table_name='check_jobs')
    op.drop_index(op.f('ix_check_jobs_id'), table_name='check_jobs')
    op.drop_table('check_jobs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
